### ISSUE TITLE
关于list.sort(key)

### ISSUE THREAD

**Issue by kokozeng** [kokozeng/DataStructure#1]
```python
s='abc00000 12345678 90000000'
s = s.split()
print("将字符串按空格分割:", s)
s.sort()
print("字符串升序:", s)
s.sort(reverse=True)
print("字符串降序:", s)


# 获取列表的第二个元素
def takeSecond(elem):
    return elem[0]
 
# 指定第二个元素排序
'''没看懂这里是什么操作, 不是takeSecond(s)吗？还有这个key在排什么序也不懂'''
s.sort(key=takeSecond)
 
# 输出类别
print ('排序列表：', s)
```
将字符串按空格分割: ['abc00000', '12345678', '90000000']
字符串升序: ['12345678', '90000000', 'abc00000']
字符串降序: ['abc00000', '90000000', '12345678']
排序列表： ['12345678', '90000000', 'abc00000']

**Comment by NCUZK** [comment]
参照理解https://blog.csdn.net/ZZh1301051836/article/details/83042214

**Comment by NCUZK** [comment]
https://selfboot.cn/2016/05/04/pythonic/
