### ISSUE TITLE
isinstance 和 type 的区别（没懂）

### ISSUE THREAD

**Issue by kokozeng** [kokozeng/DataStructure#4]
实例
```
>>>a = 111
>>> isinstance(a, int)
True
>>>
```
isinstance 和 type 的区别在于：

type()不会认为子类是一种父类类型。
isinstance()会认为子类是一种父类类型。
```
>>> class A:
...     pass
... 
>>> class B(A):
...     pass
... 
>>> isinstance(A(), A)
True
>>> type(A()) == A 
True
>>> isinstance(B(), A)
True
>>> type(B()) == A
False
```

**Comment by NCUZK** [comment]
type主要用于获取未知变量的类型
isinstance主要用于判断A类是否继承于B类

**Comment by NCUZK** [comment]
A与A（）区别：
A是一个类。例如b = A()，那么我们说b是A这个类的实例，b表示的其实就是A()。因此A()是A类的实例

**Comment by NCUZK** [comment]
总结一下：
1. 类与实例
2. 子类与父类
type只在1情况判断为True
isinstance在1和2情况都判断为True
